### ISSUE TITLE
setUserTemplate stuck loading infinite

### ISSUE THREAD

**Issue by JuanAdamuz** [mlrahman/ZKTeco_Attendance_Access_Using_PHP#2]
The function "setUserTemplate" from examples "test3.php" stucks loading forever... ¿Any clue?

**Comment by JuanAdamuz** [comment]
¿Hello? @mlrahman

**Comment by mlrahman** [comment]
Is the device connected successfully with the pc?

**Comment by JuanAdamuz** [comment]
The device is fully working and all other methods are working, this is the only function that stucks loading every time I execute it.

**Comment by JuanAdamuz** [comment]
> The device is fully working and all other methods are working, this is the only function that stucks loading every time I execute it.

@mlrahman

**Comment by JuanAdamuz** [comment]
Dont use this, broken
